FROM        hub.cdecube.com/riskctrl/riskctrlpy:base

MAINTAINER  jiabing

ADD         . /var/www/riskctrlpy

WORKDIR     /var/www/riskctrlpy

RUN         cp conf/master.py app/config.py && chmod 777 /var/log && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
                && cp conf/filebeat.yml /etc/filebeat/ && chmod go-w /etc/filebeat/filebeat.yml && chmod 777 -R /var/www
